lemonJuiceCups = float(input('Enter amount of lemon juice (in cups): \n'))
water = float(input('Enter amount of water (in cups): \n'))
agave_nectar = float(input('Enter amount of agave nectar (in cups): \n'))
servings = float(input('How many servings does this make? \n'))
print('\n')
print('Lemonade ingredients - yields 6.0 servings')
print(r'2.0 cup(s) lemon juice')
print(r'16.0 cup(s) water')
print(r'2.5 cup(s) agave nectar')
print('\n')
userinput = int(input('How many servings would you like to make?'))
print('\n')
print('Lemonade ingredients - yields', userinput, 'servings')
import math
cupsljuice = (lemonJuiceCups) * (userinput / servings)
cupsagave = (agave_nectar) * (userinput / servings)
cupswater = (water) * (userinput / servings)
print(cupsljuice, 'cup(s) lemon juice')
print(cupswater, 'cup(s) water')
print(cupsagave, 'cup(s) agave nectar')
print('\n')
print('Lemonade ingredients - yields', userinput, 'servings')
galsljuice = (cupsljuice / 16)
galswater = (cupswater / 16)
galsagave = (cupsagave / 16)